# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_intento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intento',
            name='user',
        ),
        migrations.DeleteModel(
            name='Intento',
        ),
    ]
